#ifndef TRAINCONFIG_H_
#define TRAINCONFIG_H_

#define DATALOADER_SHUFFLE_WORD_ORDER

#define RND_LENGTH 10485760 // 10m

#define RND_ST_INC1 6037
#define RND_ST_INC2 757

#define VERBOSE_EM
#define VERBOSE_GIBBS

#endif
